name: Self Hosted


on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
        

jobs:
  comment: 
    runs-on: self-hosted
    steps:
      - run: uname -a
      - uses: actions/checkout@v2
        with: 
          # will put all file under this path
          local_path: ./* # default is ./*
          # files will copy to under remote_path
          remote_path: /home/ubuntu
          
