name: Demo
#on: [push, workflow_dispatch]
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: ${{ secrets.USERNAME }} 
          server: ${{ secrets.HOST_DNS }} 
          port: ${{ secrets.PORT }}  # default is 22
          ssh_private_key: ${{ secrets.EC2_SSH_KEY }}
          local_path: ./* # default is ./*
          # files will copy to under remote_path
          remote_path: /home/ubuntu/repo
          # sftp args
          args: '-o ConnectTimeout=5'
    #steps:
      - name: Say Hello World
        run: echo Hello, world!
      # will put all file under this path
        
        
